### PR TITLE
Feature added name convention

### PR DESCRIPTION
**Pull request by rhouthuijzen**
Optimizing code after first implementation.

### CODE REVIEW

**Review by rschouten97 — APPROVED** [review]
Good additions. No further remarks

**Review by rschouten97 — APPROVED** [review]
Good additions. No further remarks

**Comment by Mauro-Bertozzi11** [comment]
Don't forget to change the readme about the correlation proces.
"You can change this behavior in the create.ps1 by setting the boolean $updatePerson to the value of $true" ->
"You can change this behavior by adjusting the updatePersonOnCorrelate within the configuration"

**Comment by Mauro-Bertozzi11** [comment]
possibly change "intus" to "intus-inplanning" in the logging for all the scripts to accomodate the other intus to intus-inplanning change

**Pull request merged**
